# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "github-pages"
group: :jekyll_plugins

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
